apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::547732776267:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::547732776267:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1HXOM9LU81L6G
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-09T11:53:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1356"
  uid: b06456d5-c684-4436-83ac-8404921c26b3
